### PR TITLE
fix(primeng): change class ui-messages-error to ui-message-error

### LINKED ISSUE #2135: Invalid validation message class name in PrimeNG
**Description**
In Formly
```
<div class="ui-message ui-messages-error" *ngIf="showError">
    <formly-validation-message [field]="field"></formly-validation-message>
</div>
```
It must be PrimeNG-specific
```
<div class="ui-message ui-message-error" *ngIf="showError">
    <formly-validation-message class="ui-message-text" [field]="field"></formly-validation-message>
</div>
```
https://primefaces.org/primeng/showcase/#/validation
PrimeNG uses ui-message-... classes for validation and ui-messages-... classes for global ones

**Environment**

- Angular version: 8.2.9
- PrimeNG version: 8.0.4
- Formly version: 5.0.0
- Formly PrimeNG version: 5.5.12

### PR DESCRIPTION
**Pull request by rternavskyi**
https://primefaces.org/primeng/showcase/#/validation
Changed class names according to documentation PrimeNG

fix #2135

### CODE REVIEW

File: src/primeng/src/lib/wrappers/form-field.ts [hunk 1]
```diff
@@ -12,12 +12,12 @@ import { FieldWrapper } from '@ngx-formly/core';
     </div>
     <ng-container #fieldComponent></ng-container>
 
-    <div class="ui-message ui-messages-error" *ngIf="showError">
-        <formly-validation-message [field]="field"></formly-validation-message>
+    <div class="ui-message ui-message-error" *ngIf="showError">
```
Comment (aitboudad) [inline src/primeng/src/lib/wrappers/form-field.ts]:
```suggestion
    <div class="ui-message ui-widget ui-corner-all ui-message-error ui-messages-error" *ngIf="showError">
```

File: src/primeng/src/lib/wrappers/form-field.ts [hunk 2]
```diff
@@ -12,12 +12,12 @@ import { FieldWrapper } from '@ngx-formly/core';
...
+        <formly-validation-message class="ui-message-text" [field]="field"></formly-validation-message>
     </div>
   `,
   styles: [`
```
Comment (aitboudad) [inline src/primeng/src/lib/wrappers/form-field.ts]: remove styles

**Comment by aitboudad** [comment]
Thank you @rternavskyi!
